window.verbs = [
  { "phaseOne": "break", "phaseTwo": "down", "inSpanish": "averiarse" },
  { "phaseOne": "break", "phaseTwo": "up", "inSpanish": "terminar una relación" },
  { "phaseOne": "bring", "phaseTwo": "up", "inSpanish": "mencionar" },
  { "phaseOne": "call", "phaseTwo": "off", "inSpanish": "cancelar" },
  { "phaseOne": "carry", "phaseTwo": "on", "inSpanish": "continuar" },
  { "phaseOne": "check", "phaseTwo": "out", "inSpanish": "revisar" },
  { "phaseOne": "come", "phaseTwo": "back", "inSpanish": "volver" },
  { "phaseOne": "come", "phaseTwo": "in", "inSpanish": "entrar" },
  { "phaseOne": "come", "phaseTwo": "up", "inSpanish": "surgir" },
  { "phaseOne": "cut", "phaseTwo": "off", "inSpanish": "cortar" },
  { "phaseOne": "do", "phaseTwo": "over", "inSpanish": "rehacer" },
  { "phaseOne": "drop", "phaseTwo": "off", "inSpanish": "dejar" },
  { "phaseOne": "end", "phaseTwo": "up", "inSpanish": "terminar" },
  { "phaseOne": "fill", "phaseTwo": "out", "inSpanish": "rellenar" },
  { "phaseOne": "find", "phaseTwo": "out", "inSpanish": "descubrir" },
  { "phaseOne": "get", "phaseTwo": "along", "inSpanish": "llevarse bien" },
  { "phaseOne": "get", "phaseTwo": "away", "inSpanish": "escapar" },
  { "phaseOne": "get", "phaseTwo": "back", "inSpanish": "recuperar" },
  { "phaseOne": "get", "phaseTwo": "by", "inSpanish": "arreglárselas" },
  { "phaseOne": "get", "phaseTwo": "through", "inSpanish": "superar" },
  { "phaseOne": "give", "phaseTwo": "up", "inSpanish": "rendirse" },
  { "phaseOne": "go", "phaseTwo": "ahead", "inSpanish": "seguir adelante" },
  { "phaseOne": "go", "phaseTwo": "back", "inSpanish": "regresar" },
  { "phaseOne": "go", "phaseTwo": "out", "inSpanish": "salir" },
  { "phaseOne": "grow", "phaseTwo": "up", "inSpanish": "crecer" },
  { "phaseOne": "hand", "phaseTwo": "out", "inSpanish": "repartir" },
  { "phaseOne": "hang", "phaseTwo": "up", "inSpanish": "colgar (teléfono)" },
  { "phaseOne": "hold", "phaseTwo": "on", "inSpanish": "esperar" },
  { "phaseOne": "keep", "phaseTwo": "on", "inSpanish": "seguir" },
  { "phaseOne": "let", "phaseTwo": "down", "inSpanish": "decepcionar" },
  { "phaseOne": "look", "phaseTwo": "after", "inSpanish": "cuidar" },
  { "phaseOne": "look", "phaseTwo": "for", "inSpanish": "buscar" },
  { "phaseOne": "look", "phaseTwo": "into", "inSpanish": "investigar" },
  { "phaseOne": "look", "phaseTwo": "up", "inSpanish": "buscar (en un diccionario)" },
  { "phaseOne": "make", "phaseTwo": "up", "inSpanish": "inventar" },
  { "phaseOne": "pick", "phaseTwo": "up", "inSpanish": "recoger" },
  { "phaseOne": "put", "phaseTwo": "off", "inSpanish": "posponer" },
  { "phaseOne": "put", "phaseTwo": "on", "inSpanish": "ponerse (ropa)" },
  { "phaseOne": "put", "phaseTwo": "down", "inSpanish": "menospreciar" },
  { "phaseOne": "run", "phaseTwo": "out", "inSpanish": "quedarse sin" },
  { "phaseOne": "set", "phaseTwo": "up", "inSpanish": "establecer" },
  { "phaseOne": "show", "phaseTwo": "up", "inSpanish": "aparecer" },
  { "phaseOne": "take", "phaseTwo": "off", "inSpanish": "despegar/quitarse" },
  { "phaseOne": "take", "phaseTwo": "over", "inSpanish": "tomar el control" },
  { "phaseOne": "turn", "phaseTwo": "down", "inSpanish": "rechazar" },
  { "phaseOne": "turn", "phaseTwo": "off", "inSpanish": "apagar" },
  { "phaseOne": "turn", "phaseTwo": "on", "inSpanish": "encender" },
  { "phaseOne": "wake", "phaseTwo": "up", "inSpanish": "despertar" },
  { "phaseOne": "work", "phaseTwo": "out", "inSpanish": "hacer ejercicio" },
  { "phaseOne": "write", "phaseTwo": "down", "inSpanish": "anotar" },
  { "phaseOne": "bring", "phaseTwo": "back", "inSpanish": "devolver" },
  { "phaseOne": "bring", "phaseTwo": "out", "inSpanish": "publicar" },
  { "phaseOne": "hold", "phaseTwo": "back", "inSpanish": "retener" }
];
